#! /bin/sh
# postinst script for ksmserver
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#

case "$1" in
    configure)
      set +e

      if [ -f "/var/lib/q4os/isquarkos.stp" ] ; then
        QEDTN1="Quarkos"
      else
        QEDTN1="Q4OS"
      fi
      QDSTRA="$( dash /usr/share/apps/q4os_system/bin/print_qaptdistr.sh )"
      echo "Distro:  [$QEDTN1, $QDSTRA]"

#       #plasma tweaks
#       CFGFL1="/usr/share/plasma/shells/org.kde.plasma.desktop/contents/defaults"
#       if [ -f "$CFGFL1" ] ; then
#         sed -i "s/org.kde.desktopcontainment/org.kde.plasma.folder/" $CFGFL1
#         sed -i "s/ToolBox=org.kde.desktoptoolbox/ToolBox=/" $CFGFL1
#       fi
#       unset CFGFL1
#       CFGFL1="/usr/share/plasma/layout-templates/org.kde.plasma.desktop.defaultPanel/contents/layout.js"
#       if [ -f "$CFGFL1" ] ; then
#         sed -i "s/panel.height = gridUnit \* 2$/panel.height = gridUnit * 2.4/" $CFGFL1
#         # sed -i 's/panel.addWidget("org.kde.plasma.kickoff")/panel.addWidget("org.kde.plasma.kicker")/' $CFGFL1
#         sed -i 's/panel.addWidget("org.kde.plasma.taskmanager")/panel.addWidget("org.kde.plasma.icontasks")/' $CFGFL1
#       fi
#       unset CFGFL1
#       #system tray icons spacing, see https://www.dedoimedo.com/computers/plasma-system-area-icon-spacing.html
#       # CFGFL1="/usr/share/plasma/plasmoids/org.kde.plasma.private.systemtray/contents/ui/main.qml"
#       # if [ -f "$CFGFL1" ] ; then
#       #   sed -i "s/spacing: 0$/spacing: 5/" $CFGFL1
#       # fi

      CFGFL1="/etc/xdg/kickoffrc"
      if [ -f "$CFGFL1" ] ; then
        if [ "$QEDTN1" = "Quarkos" ] ; then
          kwrtcfgpm --file "$CFGFL1" --group "Branding" --key "Homepage" "https://quark-os.sourceforge.io/"
          kwrtcfgpm --file "$CFGFL1" --group "Favorites" --key "FavoriteURLs" "preferred://browser,org.kde.discover.desktop,org.kde.kontact.desktop,libreoffice-startcenter.desktop,org.kde.dolphin.desktop,org.kde.plasma-systemmonitor.desktop,systemsettings.desktop,org.kde.konsole.desktop"
        else
          kwrtcfgpm --file "$CFGFL1" --group "Branding" --key "Homepage" "https://www.q4os.org/"
          kwrtcfgpm --file "$CFGFL1" --group "Favorites" --key "FavoriteURLs" "preferred://browser,org.kde.dolphin.desktop,systemsettings.desktop" #google-chrome.desktop,org.kde.discover.desktop,org.kde.kontact.desktop,org.kde.kate.desktop,libreoffice-startcenter.desktop,org.kde.plasma-systemmonitor.desktop,org.kde.konsole.desktop
        fi
        chmod a+r "$CFGFL1"
      fi
      CFGFL1="/etc/xdg/kicker-extra-favoritesrc"
      if [ -f "$CFGFL1" ] ; then
        if [ "$QEDTN1" = "Quarkos" ] ; then
          kwrtcfgpm --file "$CFGFL1" --group "General" --key "Prepend" "preferred://browser;org.kde.discover.desktop;org.kde.kontact.desktop;libreoffice-startcenter.desktop;org.kde.dolphin.desktop;org.kde.plasma-systemmonitor.desktop;systemsettings.desktop;org.kde.konsole.desktop;"
        else
          kwrtcfgpm --file "$CFGFL1" --group "General" --key "Prepend" "preferred://browser;org.kde.dolphin.desktop;systemsettings.desktop;"
        fi
        chmod a+r "$CFGFL1"
      fi
      unset CFGFL1
      # KNOWN LIMITATION (confirmed 2026-08-14, plasma-desktop/plasma-workspace 6.6.4 on resolute):
      # the next 3 blocks (taskmanager/kicker/kickoff) sed-patch a loose contents/config/main.xml
      # that no longer ships on resolute - Plasma 6 compiles each plasmoid's default config into
      # its .so (org.kde.plasma.icontasks/kicker/kickoff now only have a bare metadata.json on disk).
      # The [ -f "$CFGFL1" ] guard means these 3 blocks silently no-op there; don't assume they do
      # anything on resolute (or any future Plasma-6-only target) just because they're still here.
      CFGFL1="/usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/config/main.xml" #default task manager launchers
      if [ -f "$CFGFL1" ] ; then
        if [ "$QEDTN1" = "Quarkos" ] ; then
          sed -i "s@<default>applications:systemsettings.desktop.*@<default>applications:systemsettings.desktop,preferred://filemanager,preferred://browser</default>@" $CFGFL1
        else
          sed -i "s@<default>applications:systemsettings.desktop.*@<default></default>@" $CFGFL1
          # sed -i "s@<default>applications:systemsettings.desktop.*@<default>applications:q4os-welcome-screen5.desktop,applications:google-chrome.desktop</default>@" $CFGFL1
          # sed -i 's@kcfgfile name=""@kcfgfile name="tskmgrq4rc"@' $CFGFL1
        fi
      fi
      unset CFGFL1
      CFGFL1="/usr/share/plasma/plasmoids/org.kde.plasma.kicker/contents/config/main.xml"
      if [ -f "$CFGFL1" ] ; then
        if [ "$QEDTN1" = "Quarkos" ] ; then
          sed -i "s@<default>preferred://browser,org.kde.discover.desktop.*@<default>preferred://browser,org.kde.discover.desktop,systemsettings.desktop,org.kde.plasma-systemmonitor.desktop,org.kde.dolphin.desktop,org.kde.konsole.desktop,org.kde.kontact.desktop</default>@" $CFGFL1
        fi
      fi
      unset CFGFL1
      CFGFL1="/usr/share/plasma/plasmoids/org.kde.plasma.kickoff/contents/config/main.xml"
      if [ -f "$CFGFL1" ] ; then
        if [ "$QEDTN1" = "Quarkos" ] ; then
          sed -i "s@<default>preferred://browser,org.kde.discover.desktop.*@<default>preferred://browser,org.kde.discover.desktop,systemsettings.desktop,org.kde.plasma-systemmonitor.desktop,org.kde.dolphin.desktop,org.kde.konsole.desktop,org.kde.kontact.desktop</default>@" $CFGFL1
        fi
      fi
      unset CFGFL1
      # This only strips Discover from the org.kubuntu.desktop* look-and-feel layout (the
      # "Kubuntu" global theme, kubuntu-settings-desktop's org.kubuntu.desktop.defaultPanel
      # template). It does NOT cover stock "Breeze" (org.kde.breeze.desktop, shipped unmodified
      # by plasma-workspace-data): Breeze's own layout.js just loads the generic upstream
      # org.kde.plasma.desktop.defaultPanel template, which adds org.kde.plasma.icontasks with
      # no explicit launcher list, so it falls back to that widget's compiled-in default -
      # which unconditionally pins org.kde.discover.desktop with no installed-check. Switching
      # to plain Breeze after uninstalling plasma-discover will show a dead Discover pin; this
      # is inherent upstream behavior, not fixable here without a functional patch (KNOWN, not
      # planned - see bug report 2026-08-14).
      CFGFL1="/usr/share/plasma/layout-templates/org.kubuntu.desktop.defaultPanel/contents/layout.js"
      if [ -f "$CFGFL1" ] ; then
        if [ "$QDSTRA" = "resolute" ] ; then
          sed -i "/    app_software_str,$/d" $CFGFL1 #remove software manager icon from taskbar
        fi
      fi
      unset CFGFL1

      if [ -n "$2" ] ; then
        echo "Former package version: ($2), look like an upgrade ..."
        exit 0
      fi
      echo "Looks to be a new install ..."

      # if [ -f "/etc/q4os/q4base.conf" ] ; then
      #   BVER_FIRST="$( kreadconfig5 --file "/etc/q4os/q4base.conf" --group "OnInstall" --key "q4osbase_version" )"
      #   echo "First q4os-base version: ($BVER_FIRST)"
      #   if dpkg --compare-versions "$BVER_FIRST" lt "3.9.4-a1" ; then
      #     echo "No further action required for this system."
      #     exit 0
      #   fi
      # fi

      CFGFL1="/etc/xdg/kcm-about-distrorc"
      QCODENM="$( OPT_UPPER_FIRST=1 OPT_CODENAME=1 dash /usr/share/apps/q4os_system/bin/print_qaptdistr.sh )"
      kwrtcfgpm --file "$CFGFL1" --group "General" --key "Name" "$QEDTN1 $QCODENM"
      if [ "$QEDTN1" = "Q4OS" ] ; then
        kwrtcfgpm --file "$CFGFL1" --group "General" --key "LogoPath" "/usr/share/icons/hicolor/64x64/apps/q4oslogo2.png"
        kwrtcfgpm --file "$CFGFL1" --group "General" --key "Website" "https://q4os.org"
        QVERSN="$( get-q4os-version | awk -F'.' '{ print $1 }' )"
        kwrtcfgpm --file "$CFGFL1" --group "General" --key "Version" "$QVERSN"
      elif [ "$QEDTN1" = "Quarkos" ] ; then
        kwrtcfgpm --file "$CFGFL1" --group "General" --key "LogoPath" "/usr/share/icons/hicolor/64x64/apps/q4oslogo2.png"
        kwrtcfgpm --file "$CFGFL1" --group "General" --key "Website" "https://quark-os.sourceforge.io/"
        QVERSN="$( get-q4os-version | awk -F'.' '{ print $2".04" }' )"
        kwrtcfgpm --file "$CFGFL1" --group "General" --key "Version" "$QVERSN"
      fi
      chmod a+r "$CFGFL1"
      unset CFGFL1

      #polish for debonaire plasma theme
      if [ "$QDSTRA" = "forky" ] || [ "$QDSTRA" = "trixie" ] || [ "$QDSTRA" = "resolute" ] ; then
        CFGFL1="/etc/xdg/breezerc"
        kwrtcfgpm --file "$CFGFL1" --group "Common" --key "OutlineIntensity" "OutlineOff"
        kwrtcfgpm --file "$CFGFL1" --group "Common" --key "ShadowSize" "ShadowMedium"
        kwrtcfgpm --file "$CFGFL1" --group "Common" --key "ShadowStrength" "200"
        chmod a+r "$CFGFL1"
        unset CFGFL1
      fi

      if [ "$QDSTRA" != "bookworm" ] && [ "$QDSTRA" != "bullseye" ] && [ "$QDSTRA" != "noble" ] && [ "$QDSTRA" != "jammy" ] && [ "$QDSTRA" != "raspbian12" ] ; then
        #don't run plasma-welcome wizzard
        kwrtcfgpm --file "/etc/xdg/plasma-welcomerc" --group "General" --key "ShouldShow" "false"
        # kwrtcfgpm --file "/etc/xdg/plasma-welcomerc" --group "General" --key "LastSeenVersion" "10"
        chmod a+r /etc/xdg/plasma-welcomerc
      fi

      #override the default user avatar
      if [ "$QDSTRA" = "bullseye" ] || [ "$QDSTRA" = "jammy" ] ; then
        echo > /dev/null
      else
        # dpkg-divert --divert /usr/share/apps/q4os_system/diversions/.face --rename /etc/skel/.face #don't divert conffiles, see https://www.debian.org/doc/debian-policy/ap-pkg-diversions
        FACEFL="/usr/share/apps/q4os_system/share/.face_plasma" #/usr/share/icons/breeze/actions/22/im-user.svg
        if [ -f "$FACEFL" ] ; then
          echo "Configuring default user icon ..."
          cp "$FACEFL" /etc/skel/.face
        fi
      fi

      if [ "$QDSTRA" = "bookworm" ] || [ "$QDSTRA" = "bullseye" ] || [ "$QDSTRA" = "raspbian12" ] ; then
        update-alternatives --set x-cursor-theme /etc/X11/cursors/breeze_cursors.theme
        # update-alternatives --set desktop-plasma5-wallpaper /usr/share/something/futureprototype-theme/wallpaper
        # if [ -f "/usr/share/live-installer/logo2.png" ] ; then
        #   mv /usr/share/live-installer/logo.png /usr/share/live-installer/logo.png.tde
        #   cp /usr/share/live-installer/logo2.png /usr/share/live-installer/logo.png
        # fi
      elif [ "$QDSTRA" = "trixie" ] ; then
        echo > /dev/null
        # update-alternatives --set x-cursor-theme /usr/share/icons/DMZ-White/cursor.theme
      fi

      set -e
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

exit 0
